In [17]:
import torch

In [18]:
import numpy as np

In [19]:
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [20]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [21]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n {x_ones} \n")

Ones Tensor:
 tensor([[1, 1],
        [1, 1]]) 



In [24]:
x_rand = torch.rand_like(x_data, dtype = torch.float)

In [25]:
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.9090, 0.6116],
        [0.7895, 0.9570]]) 



In [26]:
shape = (2,3)

In [28]:
rand_tensor = torch.rand(shape)

In [29]:
print(f"Random tensor: \n {rand_tensor} \n")

Random tensor: 
 tensor([[0.2284, 0.0167, 0.5876],
        [0.3262, 0.0047, 0.6472]]) 



In [30]:
ones_tensor = torch.ones(shape)

In [31]:
print(f"ones tensor: \n {ones_tensor} \n")

ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [32]:
zeros_tensor = torch.zeros(shape)
print(f"zeros tensor: \n {zeros_tensor} \n")

zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [33]:
tensor = torch.rand(3,4)

In [34]:
print(f"shape of tensor: {tensor.shape}")

shape of tensor: torch.Size([3, 4])


In [35]:
print(f"datatype of tensor: {tensor.dtype}")

datatype of tensor: torch.float32


In [36]:
print(f"device tensor is stored on: {tensor.device}")

device tensor is stored on: cpu


In [37]:
tensor = torch.rand(3, 4, device="cuda")
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [40]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

In [41]:
tensor = torch.ones(4,4)

In [42]:
print(f"first row: {tensor[0]}")

first row: tensor([1., 1., 1., 1.])


In [43]:
print(f"first column: {tensor[:, 0]}")

first column: tensor([1., 1., 1., 1.])


In [45]:
print(f"last column: {tensor[..., -1]}")

last column: tensor([1., 1., 1., 1.])


In [46]:
tensor[:,1] = 0

In [47]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [48]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)

In [49]:
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [50]:
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [51]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
y1 = tensor @ tensor.T 

In [53]:
y2 = tensor.matmul(tensor.T)

In [54]:
y3 = torch.rand_like(y1)

In [55]:
torch.matmul(tensor, tensor.T, out = y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [56]:
z1 = tensor * tensor

In [57]:
print(z1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [58]:
z2 = tensor.mul(tensor)

In [59]:
print(z2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [60]:
z3 = torch.rand_like(tensor)

In [61]:
torch.mul(tensor, tensor, out = z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [62]:
agg = tensor.sum()

In [63]:
agg_item = agg.item()

In [64]:
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [65]:
print(f"{tensor} \n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [66]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [67]:
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [68]:
t = torch.ones(5)

In [69]:
print(f"t:{t}")

t:tensor([1., 1., 1., 1., 1.])


In [70]:
n = t.numpy()

In [71]:
print(n)

[1. 1. 1. 1. 1.]


In [72]:
t.add_(1)

print(f" t: {t}")

 t: tensor([2., 2., 2., 2., 2.])


In [73]:
print(f"n: {n}")

n: [2. 2. 2. 2. 2.]


In [74]:
n = np.ones(5)
t = torch.from_numpy(n)

In [75]:
print(n)

[1. 1. 1. 1. 1.]


In [76]:
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [77]:
np.add(n, 1, out = n)
print(f"n: {n}")

n: [2. 2. 2. 2. 2.]


In [78]:
print(f"t: {t}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
